### ISSUE TITLE
Closing channel (entering challenge period) does not work or at least event is not fired

### ISSUE THREAD

**Issue by ArjunBhuptani** [ConnextProject/ethcalate-2waypayment#97] opened 2018-04-20 19:55 UTC
Transaction confirms, but the channel does not move to challenge section.

**Comment by ArjunBhuptani** [comment] 2018-04-20 20:09
We tried this with Layne and I:

Opened channel, sent 7 tx back and forth, I updated nonce 6 on chain. Then, I closed channel (entered challenge period) with that update. On my side, the channel was still in "active" for a good 5 mins before it showed up in challenge. The channel shows balance with nonce 7 but seems to have closed correctly with 6.

What can we do about this? The 5-10 min wait for the channel to move into challenge makes it seem broken.

**Comment by ArjunBhuptani** [comment] 2018-04-20 20:37
This seems to work intermittently. I think we need more testing here, but it may be good enough for v0?

**Comment by rhlsthrm** [comment] 2018-04-20 22:04
Yep this is the same issue we have been having where the ChannelChallenge event isn't getting seen by the listener. That's why we added the refresh channel workaround. If you confirm the tx and then refresh the channel it should work.

**Comment by rhlsthrm** [comment] 2018-04-20 22:04
Duplicate of #72

**Closed by rhlsthrm** 2018-04-20 22:04 UTC
Labels: bug, duplicate
